# Generated by Django 5.1 on 2024-08-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_teamstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstats',
            name='losses',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='matches_played',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='win_percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='wins',
            field=models.IntegerField(),
        ),
    ]
