# Generated by Django 5.1 on 2024-08-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_alter_teamstats_losses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstats',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='win_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
