# Generated by Django 5.1 on 2024-08-19 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_alter_teamstats_losses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='venue',
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='matches_lost', to='scoring.teamstats'),
        ),
        migrations.AddField(
            model_name='match',
            name='score_team1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score_team2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='matches_won', to='scoring.teamstats'),
        ),
        migrations.AddField(
            model_name='player',
            name='batting_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='best_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='bowling_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='eco_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='player',
            name='fifties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='overs',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='player',
            name='thiries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='scoring.teamstats'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='scoring.teamstats'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='scoring.teamstats'),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='win_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.CreateModel(
            name='IndividualScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batting_runs', models.IntegerField(default=0)),
                ('balls_faced', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('six', models.IntegerField(default=0)),
                ('strike_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overs', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('bowling_runs', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('eco_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_scores', to='scoring.player')),
            ],
        ),
        migrations.DeleteModel(
            name='Umpire',
        ),
    ]
