# Generated by Django 5.1 on 2024-08-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0007_rename_score_scoreboard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bowlerstats',
            name='match',
        ),
        migrations.RemoveField(
            model_name='bowlerstats',
            name='player',
        ),
        migrations.DeleteModel(
            name='BatsmanStats',
        ),
        migrations.DeleteModel(
            name='BowlerStats',
        ),
    ]
