# Generated by Django 5.1 on 2024-08-20 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0008_remove_bowlerstats_match_remove_bowlerstats_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatsmanStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(default=0)),
                ('balls_faced', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0.0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.teamstats')),
            ],
        ),
        migrations.CreateModel(
            name='BowlerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overs_bowled', models.FloatField(default=0.0)),
                ('runs_given', models.IntegerField(default=0)),
                ('dot_balls', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('economy_rate', models.FloatField(default=0.0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.teamstats')),
            ],
        ),
    ]
