# Generated by Django 5.1 on 2024-08-20 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0009_batsmanstats_bowlerstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(default=0)),
                ('is_wicket', models.BooleanField(default=False)),
                ('batsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.batsmanstats')),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_teams', to='scoring.teamstats')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.bowlerstats')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_teams', to='scoring.teamstats')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.match')),
            ],
        ),
    ]
