# Generated by Django 5.1 on 2024-08-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0010_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='extra_runs',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='ball',
            name='is_byes',
            field=models.BooleanField(default=False),
        ),
    ]
