# Generated by Django 5.1 on 2024-09-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0012_alter_ball_extra_runs_setplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='is_noball',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ball',
            name='is_wide',
            field=models.BooleanField(default=False),
        ),
    ]
