# Generated by Django 5.1 on 2024-09-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0013_ball_is_noball_ball_is_wide'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowlerstats',
            name='b',
            field=models.IntegerField(default=0),
        ),
    ]
