# Generated by Django 5.1 on 2024-09-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0014_bowlerstats_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bowlerstats',
            name='b',
        ),
    ]
