# Generated by Django 5.1 on 2024-09-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0016_remove_bowlerstats_overs_bowled_bowlerstats_bowled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bowlerstats',
            old_name='bowled',
            new_name='ball1',
        ),
    ]
