# Generated by Django 5.1 on 2024-09-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0017_rename_bowled_bowlerstats_ball1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='is_legbyes',
            field=models.BooleanField(default=False),
        ),
    ]
