# Generated by Django 5.1 on 2024-09-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0018_ball_is_legbyes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='team_over',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='total_balls',
            field=models.IntegerField(default=0),
        ),
    ]
