# Generated by Django 5.1 on 2024-09-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0019_ball_team_over_alter_match_total_balls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ball',
            name='team_over',
        ),
        migrations.AddField(
            model_name='match',
            name='over_done',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
