# Generated by Django 5.1 on 2024-09-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0021_match_batting_team_score_match_batting_team_wicket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='batting_team_extra_runs',
            field=models.IntegerField(default=0),
        ),
    ]
