# Generated by Django 5.1 on 2024-09-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0022_match_batting_team_extra_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='batsmanstats',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bowlerstats',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.CharField(default='LIVE', max_length=20),
        ),
    ]
