# Generated by Django 5.1 on 2024-09-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0023_batsmanstats_name_bowlerstats_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batsmanstats',
            name='isOut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.CharField(default='LIVE', max_length=10),
        ),
    ]
