# Generated by Django 5.1 on 2024-09-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0024_batsmanstats_isout_alter_match_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='inning',
            field=models.IntegerField(default=1),
        ),
    ]
