# Generated by Django 5.1 on 2024-09-07 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0025_match_inning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='total_overs_bowled',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_inning', to='scoring.match')),
                ('inning_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seccond_inning', to='scoring.match')),
            ],
        ),
    ]
