# Generated by Django 5.1 on 2024-09-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0027_innings_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_ball',
            field=models.IntegerField(default=1),
        ),
    ]
