# Generated by Django 5.1 on 2024-09-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0028_player_total_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='batsmanstats',
            name='caughtBy',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='batsmanstats',
            name='outBy',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='batsmanstats',
            name='outType',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
