# Generated by Django 5.1 on 2024-09-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0030_alter_batsmanstats_caughtby_alter_batsmanstats_outby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batsmanstats',
            name='caughtBy',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='batsmanstats',
            name='outBy',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='batsmanstats',
            name='outType',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
