# Generated by Django 5.1 on 2024-09-14 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0031_alter_batsmanstats_caughtby_alter_batsmanstats_outby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstats',
            name='player_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='innings',
            name='inning_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_inning', to='scoring.match'),
        ),
    ]
