# Generated by Django 5.1 on 2024-09-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0032_teamstats_player_count_alter_innings_inning_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstats',
            name='player_count',
        ),
    ]
